version: '3'

services:

  auth-service:
    build:
      context: ./../auth
      dockerfile: ./../auth/auth.dockerfile
    restart: always
    ports:
      - "8082:8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - laravel

  user-service:
    build:
      context: ./../user
      dockerfile: ./../user/user.dockerfile
    restart: always
    ports:
      - "8085:8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - laravel

  blog-service:
    build:
      context: ./../blog
      dockerfile: ./../blog/blog.dockerfile
    restart: always
    ports:
      - "8083:8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - laravel

  notification-service:
    build:
      context: ./../notification
      dockerfile: ./../notification/notification.dockerfile
    restart: always
    ports:
      - "8084:8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - laravel

  db_postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: go_micro
    ports:
      - "54320:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: alimoharrami251@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - laravel

  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
    networks:
      - laravel

networks:
  laravel:
volumes:
  local_pgdata:
  pgadmin_data:
